name: Security Checks

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Bandit
        run: bandit -q -r . -x .venv,venv,__pycache__

      - name: Run pip-audit
        run: pip-audit -r requirements.txt -r requirements-dev.txt

